name: ai-vms
version: "3.8"

services:
  rabbitmq:
    image: ai-vms-rabbitmq:latest
    # build:
    #   context: ./Video_decoder/docker_env/rabbitmq
    container_name: rabbitmq_service
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - lawa_network

  postgres:
    image: postgres:15
    container_name: postgres_ai_vms
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_ROOT_PASSWORD: ${PG_ROOT_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - lawa_network

  db-init:
    image: postgres:15
    container_name: ai_vms_db_init
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      PGPASSWORD: ${PG_PASSWORD}
    volumes:
      - ./postgres-init/create_db_tables.sql:/create_db_tables.sql:ro
      - ./postgres-init/insert_default_data.sql:/insert_default_data.sql:ro
    command: >
      sh -c " psql -h postgres -U ${PG_USER} -d ${PG_DATABASE} -f /create_db_tables.sql && psql -h postgres -U ${PG_USER} -d ${PG_DATABASE} -f /insert_default_data.sql "
    networks:
      - lawa_network

  backend:
    image: ai-vms-backend:latest
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    env_file:
      - ./.env
    container_name: ai_vms_api
    working_dir: /app
    volumes:
      - ./backend/ai_vms:/app/ai_vms
      - ./Video_decoder/input:/app/input
    ports:
      - "${BACKEND_PORT}:8010"
    depends_on:
      db-init:
        condition: service_completed_successfully
    environment:
      # --- Postgres SQLAlchemy URLs ---
      DB_URL_SYNC: postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DATABASE}
      DB_URL_ASYNC: postgresql+asyncpg://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DATABASE}
      TEST_DB_URL_ASYNC: postgresql+asyncpg://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DATABASE}_test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - lawa_network

  frontend:
    image: ai-vms-frontend:latest
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    env_file:
      - ./.env
    container_name: ai_vms_frontend
    working_dir: /frontend/ai_vms
    volumes:
      - ./frontend/ai_vms:/frontend/ai_vms
      - /frontend/ai_vms/node_modules
    ports:
      - "${FRONTEND_PORT}:5173"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
    networks:
      - lawa_network

  websocket-hub:
    build:
      context: ./WebSocketService
      dockerfile: Dockerfile
    container_name: lawa_websocket_hub
    environment:
      - WEBSOCKET_PORT=9004
      - WEBSOCKET_HOST=0.0.0.0
    ports:
      - "9004:9004"
    networks:
      - lawa_network

  event-manager:
    build: 
      context: ./EventManager
      dockerfile: Dockerfile
    container_name: lawa_event_manager
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully
      websocket-hub:
        condition: service_started
    env_file:
      - ./.env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - EXCHANGE_NAME=LAWA_exchange
      - EXCHANGE_TYPE=direct
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${PG_DATABASE}
      - DB_USER=${PG_USER}
      - DB_PASSWORD=${PG_PASSWORD}
      - WEBSOCKET_HOST=websocket-hub
      - WEBSOCKET_PORT=9004
      - EVIDENCE_VIDEO_FPS=1
    volumes:
      - ./EventManager/evidence_storage:/app/evidence_storage
      - ./logs/event-manager:/app/logs
      - ./EventManager/src:/app/src
    networks:
      - lawa_network

  ai-inference-detection:
    build:
      context: ./ai-inference-detection
      dockerfile: Dockerfile
    container_name: lawa_ai_inference_detection
    ipc: shareable
    shm_size: 1gb 
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - EXCHANGE_NAME=LAWA_exchange
      - EXCHANGE_TYPE=direct
      - NUMBERS_OF_WORKER=2
      - DEVICE=cuda
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./logs/ai-inference-detection:/app/logs
      - ./Ai_services/Ai_engine/src:/app/src
    networks:
      - lawa_network

  ai-inference-classification:
      build:
        context: ./ai-inference-classification
        dockerfile: Dockerfile
      container_name: lawa_ai_inference_classification
      ipc: shareable
      shm_size: 1gb
      depends_on:
        rabbitmq:
          condition: service_healthy
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
      environment:
        - RABBITMQ_HOST=rabbitmq
        - RABBITMQ_PORT=5672
        - RABBITMQ_USERNAME=user
        - RABBITMQ_PASSWORD=password
        - EXCHANGE_NAME=LAWA_exchange
        - EXCHANGE_TYPE=direct
        - NUMBERS_OF_WORKER=2
        - DEVICE=cuda
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      volumes:
        - ./logs/ai-inference-classification:/app/logs
        - ./Ai_services/Ai_engine/src:/app/src
      networks:
        - lawa_network

  ai-inference-segmentation:
    build:
      context: ./ai-inference-segmentation
      dockerfile: Dockerfile
    container_name: lawa_ai_inference_segmentation
    ipc: shareable
    shm_size: 1gb
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - EXCHANGE_NAME=LAWA_exchange
      - EXCHANGE_TYPE=direct
      - NUMBERS_OF_WORKER=2
      - DEVICE=cuda
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./logs/ai-inference-segmentation:/app/logs
      - ./Ai_services/Ai_engine/src:/app/src
    networks:
      - lawa_network
 

  ai-crowd-density:
    build:
      context: ./ai-crowd-density
      dockerfile: Dockerfile
    container_name: lawa_ai_crowd_density
    # ipc: service:ai-inference-detection
    # ipc: service:ai-inference-classification
    ipc: service:ai-inference-segmentation
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - EXCHANGE_NAME=LAWA_exchange
      - EXCHANGE_TYPE=direct
      - QUEUE_NAME=queue_crowd_density
      - EVENT_MANAGER_QUEUE=crowd_density_event_queue
    volumes:
      - ./logs/ai-crowd-density:/app/logs
      - ./Ai_services/Ai_engine/src:/app/src
    networks:
      - lawa_network

  # ai-bird-eye-view:
  #   build:
  #     context: ./ai-bird-eye-view
  #     dockerfile: Dockerfile
  #   container_name: lawa_ai_bird_eye_view
  #   ipc: service:ai-inference-detection
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_PORT=5672
  #     - RABBITMQ_USERNAME=user
  #     - RABBITMQ_PASSWORD=password
  #     - EXCHANGE_NAME=LAWA_exchange
  #     - EXCHANGE_TYPE=direct
  #     - QUEUE_NAME=queue_bird_eye_view
  #     - EVENT_MANAGER_QUEUE=bird_eye_view_event_queue
  #   volumes:
  #     - ./logs/ai-bird-eye-view:/app/logs
  #     - ./Ai_services/Ai_engine/src:/app/src
  #   networks:
  #     - lawa_network

  # ai-in-out-person-count:
  #   build:
  #     context: ./ai-in-out-person-count
  #     dockerfile: Dockerfile
  #   container_name: lawa_ai_in_out_person_count
  #   ipc: service:ai-inference-detection
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_PORT=5672
  #     - RABBITMQ_USERNAME=user
  #     - RABBITMQ_PASSWORD=password
  #     - EXCHANGE_NAME=LAWA_exchange
  #     - EXCHANGE_TYPE=direct
  #     - QUEUE_NAME=queue_in_out_person_count
  #     - EVENT_MANAGER_QUEUE=in_out_person_count_event_queue
  #   volumes:
  #     - ./logs/ai-in-out-person-count:/app/logs
  #     - ./Ai_services/Ai_engine/src:/app/src
  #   networks:
  #     - lawa_network

  # ai-loitering-detection:
  #   build:
  #     context: ./ai-loitering-detection
  #     dockerfile: Dockerfile
  #   container_name: lawa_ai_loitering_detection
  #   ipc: service:ai-inference-detection
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_PORT=5672
  #     - RABBITMQ_USERNAME=user
  #     - RABBITMQ_PASSWORD=password
  #     - EXCHANGE_NAME=LAWA_exchange
  #     - EXCHANGE_TYPE=direct
  #     - QUEUE_NAME=queue_loitering_detection
  #     - EVENT_MANAGER_QUEUE=loitering_detection_event_queue
  #   volumes:
  #     - ./logs/ai-loitering-detection:/app/logs
  #     - ./Ai_services/Ai_engine/src:/app/src
  #   networks:
  #     - lawa_network

  # ai-person-count-inside-compartment:
  #   build:
  #     context: ./ai-person-count-inside-compartment
  #     dockerfile: Dockerfile
  #   container_name: lawa_ai_person_count_inside_compartment
  #   ipc: service:ai-inference-detection
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_PORT=5672
  #     - RABBITMQ_USERNAME=user
  #     - RABBITMQ_PASSWORD=password
  #     - EXCHANGE_NAME=LAWA_exchange
  #     - EXCHANGE_TYPE=direct
  #     - QUEUE_NAME=queue_person_count_inside_compartment
  #     - EVENT_MANAGER_QUEUE=person_count_inside_compartment_event_queue
  #   volumes:
  #     - ./logs/ai-person-count-inside-compartment:/app/logs
  #     - ./Ai_services/Ai_engine/src:/app/src
  #   networks:
  #     - lawa_network

  # ai-person-entered-inside-train:
  #   build:
  #     context: ./ai-person-entered-inside-train
  #     dockerfile: Dockerfile
  #   container_name: lawa_ai_person_entered_inside_train
  #   ipc: service:ai-inference-detection
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_PORT=5672
  #     - RABBITMQ_USERNAME=user
  #     - RABBITMQ_PASSWORD=password
  #     - EXCHANGE_NAME=LAWA_exchange
  #     - EXCHANGE_TYPE=direct
  #     - QUEUE_NAME=queue_person_entered_inside_train
  #     - EVENT_MANAGER_QUEUE=person_entered_inside_train_event_queue
  #   volumes:
  #     - ./logs/ai-person-entered-inside-train:/app/logs
  #     - ./Ai_services/Ai_engine/src:/app/src
  #   networks:
  #     - lawa_network

  # ai-queue-management:
  #   build:
  #     context: ./ai-queue-management
  #     dockerfile: Dockerfile
  #   container_name: lawa_ai_queue_management
  #   ipc: service:ai-inference-detection
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_PORT=5672
  #     - RABBITMQ_USERNAME=user
  #     - RABBITMQ_PASSWORD=password
  #     - EXCHANGE_NAME=LAWA_exchange
  #     - EXCHANGE_TYPE=direct
  #     - QUEUE_NAME=queue_queue_management
  #     - EVENT_MANAGER_QUEUE=queue_management_event_queue
  #   volumes:
  #     - ./logs/ai-queue-management:/app/logs
  #     - ./Ai_services/Ai_engine/src:/app/src
  #   networks:
  #     - lawa_network

  # ai-restroom-person-tracking:
  #   build:
  #     context: ./ai-restroom-person-tracking
  #     dockerfile: Dockerfile
  #   container_name: lawa_ai_restroom_person_tracking
  #   ipc: service:ai-inference-detection
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_PORT=5672
  #     - RABBITMQ_USERNAME=user
  #     - RABBITMQ_PASSWORD=password
  #     - EXCHANGE_NAME=LAWA_exchange
  #     - EXCHANGE_TYPE=direct
  #     - QUEUE_NAME=queue_restroom_person_tracking
  #     - EVENT_MANAGER_QUEUE=restroom_person_tracking_event_queue
  #   volumes:
  #     - ./logs/ai-restroom-person-tracking:/app/logs
  #     - ./Ai_services/Ai_engine/src:/app/src
  #   networks:
  #     - lawa_network

  # ai-tailgate-detection:
  #   build:
  #     context: ./ai-tailgate-detection
  #     dockerfile: Dockerfile
  #   container_name: lawa_ai_tailgate_detection
  #   ipc: service:ai-inference-detection
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_PORT=5672
  #     - RABBITMQ_USERNAME=user
  #     - RABBITMQ_PASSWORD=password
  #     - EXCHANGE_NAME=LAWA_exchange
  #     - EXCHANGE_TYPE=direct
  #     - QUEUE_NAME=queue_tailgate_detection
  #     - EVENT_MANAGER_QUEUE=tailgate_detection_event_queue
  #   volumes:
  #     - ./logs/ai-tailgate-detection:/app/logs
  #     - ./Ai_services/Ai_engine/src:/app/src
  #   networks:
  #     - lawa_network

  # ai-train-arrival-depart-monitor:
  #   build:
  #     context: ./ai-train-arrival-depart-monitor
  #     dockerfile: Dockerfile
  #   container_name: lawa_ai_train_arrival_depart_monitor
  #   ipc: service:ai-inference-detection
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_PORT=5672
  #     - RABBITMQ_USERNAME=user
  #     - RABBITMQ_PASSWORD=password
  #     - EXCHANGE_NAME=LAWA_exchange
  #     - EXCHANGE_TYPE=direct
  #     - QUEUE_NAME=queue_train_arrival_depart_monitor
  #     - EVENT_MANAGER_QUEUE=train_arrival_depart_monitor_event_queue
  #   volumes:
  #     - ./logs/ai-train-arrival-depart-monitor:/app/logs
  #     - ./Ai_services/Ai_engine/src:/app/src
  #   networks:
  #     - lawa_network

  video_decoder:
    # image: ai-vms-video_decoder:latest
    build:
      context: ./Video_decoder
      dockerfile: Dockerfile
    container_name: ai_vms_video_decoder
    restart: unless-stopped
    network_mode: host
    env_file:
      - ./.env
    environment:
      PG_HOST: localhost
      PG_PORT: "5432"
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
      RABBITMQ_HOST: localhost
      RABBITMQ_PORT: "5672"
      PYTHONUNBUFFERED: "1"
      HOST_APP_PATH: ${PWD}/Video_decoder
    depends_on:
      db-init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
      backend:
        condition: service_started
      frontend:
        condition: service_started
    volumes:
      - ./Video_decoder/config.yaml:/app/config.yaml:ro
      - ./Video_decoder/input:/app/input
      - ./Video_decoder/logs:/app/logs
      - ./Video_decoder:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/dri:/dev/dri
    privileged: true
    user: "0:0"

volumes:
  postgres_data:
  rabbitmq_data:
  event_evidence:

networks:
  lawa_network:
    driver: bridge
